Add `string.Contains` utilities
Faithlife/FaithlifeUtility pull request #49
Opened 2021-11-12 23:34 UTC by TyMick

Would the following new `string` extensions be desirable?

```c#
bool ContainsOrdinal(this string source, char value);
bool ContainsOrdinal(this string source, string value);
bool ContainsAllOrdinal(this string source, IEnumerable<string> values);
bool ContainsAllOrdinal(this string source, params string[] values);
bool ContainsAll(this string source, IEnumerable<string> values, StringComparison comparisonType);
```

Specifically, I found myself wanting to use a `bool ContainsAllOrdinal(this string source, params string[] values)` in my work today.

I'll add a few tests if these are approved in general; I just wanted to make sure they're wanted before I take the time.

2021-11-12 23:36 UTC, TyMick commented on src/Faithlife.Utility/StringUtility.cs
> +#endif
Didn't think this one would be useful enough in .NET Standard 2.0 to bother adding our own implementation of `String.Contains(String, StringComparison)`.

2021-11-12 23:47 UTC, ejball commented
`ContainsOrdinal` is a good addition, since .NET 6 analyzers complain when `Contains` is called without a comparison, and we have other `Ordinal` equivalents of `string` methods.

`ContainsAll` is debatable, since one could argue that the inline LINQ is fairly short and clear, and I would think rarely used. (In fact, `string.Contains` is often the wrong solution even for one string; I'd be interested to know the use case.)

I think we should consider the two changes separately.

2021-11-12 23:48 UTC, bgrainger commented
`ContainsAll(Ordinal)` doesn't pass the bar (for me) of being generally useful enough to add as an extension method on `string` for all Faithlife.Utility consumers, particularly when the most common variant simply boils down to `values.All(source.ContainsOrdinal)`.

The goal of Faithlife.Utility should be very commonly reused utility methods, not a "DRY dumping ground" for anything that could possibly ever be used by two or more projects.

2021-11-13 01:19 UTC, TyMick commented
All good points! I don't think realized it was as easy as `values.All(source.Contains)` when I started, and by the time I refined it to that, I'd forgotten why I wanted it in the first place. 🙈 I'll remove those `ContainsAll` variants. 👍🏼

2021-11-13 02:26 UTC, TyMick commented
And @ejball, I was using `string.Contains` in general for checking [if an email HTML string contains](https://git.faithlife.dev/TyMick/NotificationServices/blob/f9e0478386bab507378a202e022d2f22f1ed9940/tests/Logos.NotificationServices.Tests.UnitTests/Subscriber/AffirmationTests.cs#L146) a couple of test usernames.

2021-11-13 03:16 UTC, TyMick commented on tests/Faithlife.Utility.Tests/StringUtilityTests.cs
> +			Assert.IsFalse("abc".ContainsOrdinal("cd"));
I tried adding a `Assert.IsTrue("ábá".Contains("a\u0301"));` line up in the "demonstrate the problem" section but was surprised to find that it was actually false in all four target frameworks. 🤷🏼‍♂️

2021-11-13 18:44 UTC, bgrainger commented on src/Faithlife.Utility/StringUtility.cs
> +		/// Calls string.Contains with StringComparison.Ordinal.
This isn't true, based on the code below.

The comment should describe the purpose and output of the method, not its implementation. E.g., "Returns true if the string contains the specified character, using ordinal comparison."

2021-11-13 18:45 UTC, bgrainger commented on src/Faithlife.Utility/StringUtility.cs
> +#if NETSTANDARD2_0
When the comment correctly describes the _meaning_ of the method, then we no longer need this `#if` block: the description of the method shouldn't change between target frameworks.

2021-11-13 18:46 UTC, bgrainger commented on src/Faithlife.Utility/StringUtility.cs
> +			source.Contains(value);
This calls `Enumerable.Contains<char>(this IEnumerable<char> source, char value);`, which is likely not an efficient way to implement this functionality.

```suggestion
			source.IndexOf(value) != -1
```

2021-11-13 18:49 UTC, bgrainger commented on src/Faithlife.Utility/StringUtility.cs
> +		public static bool ContainsOrdinal(this string source, char value) =>
This is exactly the same as `string.Contains(char)`: https://docs.microsoft.com/en-us/dotnet/api/system.string.contains?view=net-5.0#System_String_Contains_System_Char_

We shouldn't needlessly duplicate framework methods. It'd be OK to add a `Contains(this string, char value)` extension method for downlevel frameworks, but we should normalise the understanding that `Contains(char)` and `IndexOf(char)` _are_ ordinal comparisons.

2021-11-13 18:51 UTC, bgrainger commented on src/Faithlife.Utility/StringUtility.cs
> +		public static bool ContainsOrdinal(this string source, string value) =>
Unnecessary duplicate of `string.Contains`, which has always performed an ordinal comparison; delete.

https://docs.microsoft.com/en-us/dotnet/api/system.string.contains?view=netframework-4.8#System_String_Contains_System_String_

2021-11-13 18:51 UTC, bgrainger requested changes
Delete `ContainsOrdinal`; add `string.Contains(char)` extension method for target frameworks that need it.

2021-11-13 18:54 UTC, bgrainger commented
> ContainsOrdinal is a good addition, since .NET 6 analyzers complain when Contains is called without a comparison

They do? Our Faithlife.Analyzers is smart enough to ignore `IndexOf(char)`, but if it alerts on `Contains`, we should fix it.

2021-11-13 23:37 UTC, ejball commented
> They do?

My bad. I thought I remembered that they did, but I just confirmed that they don't. It is hard to remember that `IndexOf(string)` is current-culture-sensitive but `Contains(string)` is not, so one could make the argument that `ContainsOrdinal` is more clear, but I don't feel strongly about it.

2021-11-14 00:10 UTC, bgrainger commented
Why remember when an analyser can tell you? 😀

https://github.com/Faithlife/FaithlifeAnalyzers/wiki/FL0002
https://github.com/Faithlife/FaithlifeAnalyzers/blob/d6a7a54b484dd81e8bfe56c30b3c97b5e148a8e8/tests/Faithlife.Analyzers.Tests/OverloadWithStringComparisonTests.cs#L143

2021-12-09 22:44 UTC, TyMick commented
> add `string.Contains(char)` extension method only for target frameworks that need it

In .NET Standard 2.0 (the only target framework that doesn't have a `String.Contains(Char)` method), it turns out `string.Contains(char)` gets caught by [`Enumerable.Contains<T>(this IEnumerable<T>, T)`](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.contains?view=netstandard-2.0#System_Linq_Enumerable_Contains__1_System_Collections_Generic_IEnumerable___0____0_), since `String` implements `IEnumerable<Char>`. Would the following extension be more desirable so we can call `String.Contains(String)` instead?

```c#
#if NETSTANDARD2_0
public static bool Contains(this string source, char value) =>
    source.Contains(value.ToString());
#endif
```

Or is `Enumerable.Contains` sufficient and I should just close this PR? 👌🏼

2021-12-09 23:43 UTC, ejball commented
`Enumerable.Contains` seems good enough to me.

2021-12-14 00:39 UTC, closed without merging